version: '2'
services:
  #  watchtower:
  #    image: containrrr/watchtower
  #    volumes:
  #      - /var/run/docker.sock:/var/run/docker.sock
  backend:
    image: o2buzzle/oner-backend:latest
  frontend:
    image: o2buzzle/oner-frontend:latest
  proxy:
    image: o2buzzle/oner-proxy:latest
    links:
      - "backend:api_server"
      - "frontend:frontend_host"
    depends_on:
      - backend
      - frontend
    ports:
      - "80:80"

#    labels:
#      com.centurylinklabs.watchtower.depends-on: "backend,frontend"
