name: Default CI workflow

# Controls when the workflow will run
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
          
      - name: Frontend testing
        run: echo JSLint and Jest?
      
      - name: Backend testing
        run: echo Pytest?
        
      - name: Upload test results
        run: echo upload test result
        
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - name: Package frontend
        run: echo npm/yarn build

      # Runs a set of commands using the runners shell
      - name: Package backend
        run: echo Pyproject?
      
      - name: Upload Artifacts
        run: echo Upload CD Artifacts
