name: Docker Image CI

on:
  push:
    branches: [ main ]
  workflow_dispatch:
    
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repo 
      uses: actions/checkout@v3
      with:
        submodules: true
    - name: Build the image for the nginx proxy
      working-directory: ./nginx-proxy
      run: docker build . --file Dockerfile --tag o2buzzle/oner-proxy
    - name: Docker Login
      uses: docker/login-action@v2.0.0
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}
    - name: Push to Docker Hub
      run: docker push o2buzzle/oner-proxy
    
