# This is a basic workflow to help you get started with Actions

name: Test Docker Compose File
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.REPO_PAT }}
      - name: Check Compose File
        run: docker-compose -f docker-compose.yml config
